import { LOGGED_OUT as logged_out } from '../auth/actionTypes';

export const LOADING_PATIENTS = 'home/LOADING_PATIENTS';
export const PATIENTS_AVAILABLE = 'home/PATIENTS_AVAILABLE';

export const LOADING_TASKS = 'home/LOADING_TASKS';
export const TASKS_AVAILABLE = 'home/TASKS_AVAILABLE';

export const LOADING_CALENDARITEMS = 'home/LOADING_CALENDARITEMS';
export const CALENDARITEMS_AVAILABLE = 'home/CALENDARITEMS_AVAILABLE';

export const LOADING_SUCCESSIONITEMS = 'home/LOADING_SUCCESSIONITEMS';
export const SUCCESSIONITEMS_AVAILABLE = 'home/SUCCESSIONITEMS_AVAILABLE';

export const LOADING_HISTORYITEMS = 'home/LOADING_HISTORYITEMS';
export const HISTORYITEMS_AVAILABLE = 'home/HISTORYITEMS_AVAILABLE';

export const LOADING_PROFILEITEMS = 'home/LOADING_PROFILEITEMS';
export const PROFILEITEMS_AVAILABLE = 'home/PROFILEITEMS_AVAILABLE';

export const LOADING_MEDICATIONITEMS = 'home/LOADING_MEDICATIONITEMS';
export const MEDICATIONITEMS_AVAILABLE = 'home/MEDICATIONITEMS_AVAILABLE';

export const LOGGED_OUT = logged_out;
